### ISSUE TITLE
CommonHTML does not produce output

### ISSUE THREAD

**Issue by zorkow** [pkra/mathjax-node-sre#26]
I get undefined for:

```bash
> node_modules/.bin/mjsre --output CommonHTML "x^2"
```

**Comment by pkra** [comment]
https://github.com/pkra/mathjax-node-sre/blob/6cbdd9f27de81f6610ef239a92dd978373a1bf05/bin/mjsre.js#L124

needs to be fixed.

**Comment by pkra** [comment]
Release is in progress but travis is stuck installing nvm...

**Comment by zorkow** [comment]
Don't release that. I've got a cleaner fix.
