### ISSUE TITLE
Newer MathJax SVG options are not exposed; such as blacker

### ISSUE THREAD

**Issue by stroobandt** [pkra/mathjax-node-sre#49]
[Newer MathJax SVG options](https://docs.mathjax.org/en/v2.7-latest/options/output-processors/SVG.html) are not exposed.

Especially the SVG option `blacker`, [appears to be very useful](https://www.princexml.com/forum/topic/4116/svg-output-differs-between-browser-and-prince).

**Comment by pkra** [comment]
> Newer MathJax SVG options are not exposed.

Actually, they are. Per the readme:
 
> In addition to the usual mathjax-node configuration options, mathjax-node-sre accepts...

And per the [mathajx-node readme](https://github.com/mathjax/MathJax-node#configoptions), the config accepts a MathJax object where you'd configure such things. I personally set blacker to 0 in all my projects without issue. If you have an issue, it's likely a mathjax-node problem so I'm closing this for now.

**Comment by stroobandt** [comment]
Good to know!
I am actually an indirect user of `mathjax-node-sre` through [`mathjax-node-cli`]().
The latter is used by quite some people, but development went dormant.

In `mathjax-node-cli`, the `blacker` option is definitely [not exposed yet](https://github.com/mathjax/mathjax-node-cli/issues/15).
